<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.example.demo</groupId>
        <artifactId>demo-testing</artifactId>
        <version>0.31.0-SNAPSHOT</version>
    </parent>
    <artifactId>demo-test-azure</artifactId>
    <version>0.31.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>org.example.demo</groupId>
            <artifactId>demo-test-core</artifactId>
            <version>0.31.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
